version: "3.5"
services:
  dummyweb:
    container_name: dummyweb_server
    build:
      context: .
      dockerfile: docker/Dockerfile-webapp
    image: dummyweb
    ports:
      - "8080:8080"
    environment:
      - DUMMY_SECRET=43
    networks:
      - dummy_network
  smartyweb:
    container_name: smartyweb_server
    build:
      context: .
      dockerfile: docker/Dockerfile-smarty
    image: smartyweb
    ports:
      - "8081:8081"
    networks:
      - dummy_network

networks:
  dummy_network:
    name: "my_dummy_network"
    driver: bridge
