version: "3.5"

services:
  dummyweb:
    container_name: $DUMMY_HOST
    build:
      context: .
      dockerfile: docker/dummy.Dockerfile
    image: dummyweb
    ports:
      - "$DUMMY_PORT:8080"
    environment:
      - DUMMY_SECRET=43
      - SMARTY_HOST=$SMARTY_HOST
      - SMARTY_PORT=$SMARTY_PORT
    networks:
      - dummy_network
  smartyweb:
    container_name: $SMARTY_HOST
    build:
      context: .
      dockerfile: docker/smarty.Dockerfile
    image: smartyweb
    ports:
      - "$SMARTY_PORT:8081"
    networks:
      - dummy_network

networks:
  dummy_network:
    name: "$NETWORK_NAME"
    driver: bridge
