version: "3.5"
services:
  dummyweb:
    container_name: dummyweb_server
    build:
      context: .
      dockerfile: docker/Dockerfile-webapp
    image: dummyweb
    command: "-n 42"
    ports:
      - "8080:8080"
    environment:
      - DUMMY_SECRET=43
    networks:
      - dummy_network

networks:
  dummy_network:
    name: "my_dummy_network"
    driver: bridge
